language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
env:
  - GIT_COMMIT_SHA=$TRAVIS_COMMIT GIT_BRANCH=$TRAVIS_BRANCH

install:
  - composer install --dev --no-scripts
script:
  - ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - php ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - ./cc-test-reporter after-build --exit-code 0

notifications:
  slack:
    secure: amurga3WFmDsQk7yDtptz87KBh3ufhCOQ2u9NtAsi5fhSfTQFPA5ffxsitbru23oMKC57fp0zsHshtWOLBojWi9LjqoIgs6bLdwLn0qUzDtKbvaRWdONbZTyRT8hiK/vSzB+4IaXNmYMK24wBDiF0AK77+PAeKIEUXRzVoDvqFs=
  email: false
