language: php
php:
  - 5.6
  - 7.0
notifications:
  email: false
install:
  - composer install --dev --no-scripts
script:
  - ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - php ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - ./vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
notifications:
  slack: keboola:5eSaah061XMWdUXA7swHBhtP
