name: Syrup PHP Client
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.4
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Composer install
        run: |
          composer install --dev --no-scripts
      - name: Check codestyle
        run: |
          ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
      - name: Run Tests
        run: |
          php ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
